Task/gd 129
IT-Siberians/AuthenticationMicroservice pull request #2
Opened 2024-08-18 14:09 UTC by NikeTorchwood

Fixed:
1) Removed nullable fields where they are not needed
2) Changed the returned status codes in the Presentation layer
3) Added attributes to methods showing the received status codes from the method in the Presentation layer
4) Removed unnecessary comments (those that make sense only to me), added where help is needed, controversial points or there are questions
5) Added comments in the Domain layer where they are not (documentation)
6) Reworked the Password Hasher class, removed non-obvious methods and ways of hashing the password
7) Reworked the Application layer, removed exceptions (as much as possible - only exceptional situations remain) from UserManagementService, removed checks and searches from the Application layer moved to the Presentation layer.
8) Added FluentValidation to the Presentation layer, moved the check for uniqueness of the name and email (where possible) to validation.
9) Cleaned the code for unnecessary spaces, the absence of unnecessary spaces, etc. (according to comments on the purity of the code)
10) Removed unnecessary classes (at the moment)

2024-08-20 11:25 UTC, Barmalej24 requested changes
Код понравился. Есть небольшие пожелания по исправлению

2024-08-20 11:25 UTC, Barmalej24 commented on Application/Services.Implementations/UserManagementService.cs
> +            throw new ArgumentNullException(nameof(changeUsernameModel)); // Вопрос уместно ли здесь исключение или лучше вернуть false?
можно bool значения

2024-08-20 11:25 UTC, Barmalej24 commented on Application/Services.Implementations/UserManagementService.cs
> +            throw new ArgumentNullException(nameof(changePasswordModel)); // Вопрос уместно ли здесь исключение или лучше вернуть false?
можно bool значения

2024-08-20 11:25 UTC, Barmalej24 commented on Application/Services.Implementations/UserManagementService.cs
> +            throw new ArgumentNullException(nameof(verifyEmailModel)); // Вопрос уместно ли здесь исключение или лучше вернуть false?
можно bool значения

2024-08-20 11:25 UTC, Barmalej24 commented on Infrastructure/EntityFramework/UserDbContext.cs
> +            .HasColumnName("Email")
можно не использовать явное наименование, тк имя в точности соответсвует назнанию поля

2024-08-20 11:25 UTC, Barmalej24 commented on Infrastructure/EntityFramework/UserDbContext.cs
> +            .HasColumnName("Username")
можно не использовать явное наименование, тк имя в точности соответсвует назнанию поля

2024-08-20 11:25 UTC, Barmalej24 commented on Infrastructure/EntityFramework/UserDbContext.cs
> +            .HasColumnName("PasswordHash")
можно не использовать явное наименование, тк имя в точности соответсвует назнанию поля

2024-08-20 11:25 UTC, Barmalej24 commented on Domain/Domain.Entities/IEntity.cs
> +public interface IEntity<out TId>
ограничить входящие значения структурой

2024-08-20 11:25 UTC, Barmalej24 commented on Infrastructure/Repositories.Implementations/EntityFrameworkRepositories/BaseEntityFrameworkRepository.cs
> +        EntitySet.Remove(entityToDelete);
жесткое удаление пользователя? не предусмотрено IsRemove или иного статуса?

2024-08-20 11:25 UTC, Barmalej24 commented on WebApi/WebApiAuthenticate/Controllers/UsersController.cs
> +[Route("/api/v1/[controller]")]
[controller]/[action], позволит автоматически использовать имена методов, отпадет необходимость именование в ручную в атрибутах

2024-08-23 08:01 UTC, oleggolen commented on Application/Repositories.Abstractions/IBaseRepository.cs
> +public interface IBaseRepository<T, in TId>
Согласен

2024-08-23 08:03 UTC, oleggolen commented on Application/Repositories.Abstractions/IUserRepository.cs
> +
Согласен, но и не уверен, что это ответственность репозитория, так как репозиторий - это просто хранилище эммитация базы данных, как просто коллекции объектов, эти методы явно не являются методами коллекции, а являются частью бизнес логики, поэтому их реализацию я бы перенёс просто в бизнес логику, а здесь бы добавил например выбор пользователя с указанным UserName или Email

2024-08-23 08:04 UTC, oleggolen commented on Application/Services.Abstractions/IPasswordHasher.cs
> +    public bool VerifyHashedPassword(string password, string hashedPassword);
Согласен и не понятно, что это вообще делает

2024-08-23 08:05 UTC, oleggolen commented on Application/Services.Abstractions/IUserManagementService.cs
> +    public Task<UserReadModel> GetUserByIdAsync(Guid id);
Да плюс документация по всем методам и интерфейсу

2024-08-23 09:13 UTC, oleggolen requested changes
В целом всё стало уже достаточно хорошо, много документирования кода, классная валидация, структура чистой архитектуры, убраны неочевидные вещи из кода, хорошая информативность у контроллеров. Стоит добавить исключения доменной области, чтобы сделать информацию более информативной, не бросать произвольные исключения на уровне приложения, сделать иерархию моделей, выделить общность, и соответственно их сократить, использовать инкапсуляцию,. Ещё следует быть более точным в наименованиях классов и пространств имён. Также подумать как распилить один огромный UserService, который очевидно нарушает SOLID, и выглядит, как "кашки наружу". Очень надеюсь, что полученные комментарии помогут написать хороший, документированный ООПшеый код по SOLID и применить все прелести чистой архитектуры

2024-08-23 09:13 UTC, oleggolen commented on WebApi/WebApiAuthenticate/ModelsValidators/BaseValidators/AvailableUsernameValidator.cs
> +namespace WebApiAuthenticate.ModelsValidators.BaseValidators;
Лучше изесь использовать не BaseValiators, так как слово Base предполагает в себе наличие иерерхии наследования, и действия для базовых типов. Лучше использовать что-то типо ObjectsValidatiors или PrimitiveValidators, или ещё как-то

2024-08-23 09:13 UTC, oleggolen commented on WebApi/WebApiAuthenticate/ModelsValidators/BaseValidators/EmailValidator.cs
> +namespace WebApiAuthenticate.ModelsValidators.BaseValidators;
Лучше изесь использовать не BaseValiators, так как слово Base предполагает в себе наличие иерерхии наследования, и действия для базовых типов. Лучше использовать что-то типо ObjectsValidatiors или PrimitiveValidators, или ещё как-то

2024-08-23 09:13 UTC, oleggolen commented on WebApi/WebApiAuthenticate/ModelsValidators/BaseValidators/IdValidator.cs
> +namespace WebApiAuthenticate.ModelsValidators.BaseValidators;
Лучше изесь использовать не BaseValiators, так как слово Base предполагает в себе наличие иерерхии наследования, и действия для базовых типов. Лучше использовать что-то типо ObjectsValidatiors или PrimitiveValidators, или ещё как-то

2024-08-23 09:13 UTC, oleggolen commented on WebApi/WebApiAuthenticate/ModelsValidators/BaseValidators/PasswordValidator.cs
> +namespace WebApiAuthenticate.ModelsValidators.BaseValidators;
Лучше изесь использовать не BaseValiators, так как слово Base предполагает в себе наличие иерерхии наследования, и действия для базовых типов. Лучше использовать что-то типо ObjectsValidatiors или PrimitiveValidators, или ещё как-то

2024-08-23 09:13 UTC, oleggolen commented on WebApi/WebApiAuthenticate/ModelsValidators/BaseValidators/UsernameValidator.cs
> +namespace WebApiAuthenticate.ModelsValidators.BaseValidators;
Лучше изесь использовать не BaseValiators, так как слово Base предполагает в себе наличие иерерхии наследования, и действия для базовых типов. Лучше использовать что-то типо ObjectsValidatiors или PrimitiveValidators, или ещё как-то

2024-08-23 09:13 UTC, oleggolen commented on WebApi/WebApiAuthenticate/Models/ChangeEmailRequest.cs
> +namespace WebApiAuthenticate.Models;
Переименовать в Requests

2024-08-23 09:13 UTC, oleggolen commented on WebApi/WebApiAuthenticate/Models/ChangePasswordRequest.cs
> +﻿namespace WebApiAuthenticate.Models;
Переименовать в Requests

2024-08-23 09:13 UTC, oleggolen commented on WebApi/WebApiAuthenticate/Models/ChangeUsernameRequest.cs
> +﻿namespace WebApiAuthenticate.Models;
Переименовать в Requests

2024-08-23 09:13 UTC, oleggolen commented on WebApi/WebApiAuthenticate/Models/CreatingUserRequest.cs
> +﻿namespace WebApiAuthenticate.Models;
Переименовать в Requests

2024-08-23 09:13 UTC, oleggolen commented on WebApi/WebApiAuthenticate/Models/VerifyEmailRequest.cs
> +﻿namespace WebApiAuthenticate.Models;
Переименовать в Requests

2024-08-23 09:13 UTC, oleggolen commented on WebApi/WebApiAuthenticate/ModelsValidators/BaseValidators/AvailableEmailValidator.cs
> +namespace WebApiAuthenticate.ModelsValidators.BaseValidators;
И переименовать в ReuestsValidators

2024-08-23 09:13 UTC, oleggolen commented on WebApi/WebApiAuthenticate/ModelsValidators/BaseValidators/AvailableUsernameValidator.cs
> +namespace WebApiAuthenticate.ModelsValidators.BaseValidators;
И переименовать в ReuestsValidators

2024-08-23 09:13 UTC, oleggolen commented on WebApi/WebApiAuthenticate/ModelsValidators/BaseValidators/EmailValidator.cs
> +namespace WebApiAuthenticate.ModelsValidators.BaseValidators;
И переименовать в ReuestsValidators

2024-08-23 09:13 UTC, oleggolen commented on WebApi/WebApiAuthenticate/ModelsValidators/BaseValidators/IdValidator.cs
> +namespace WebApiAuthenticate.ModelsValidators.BaseValidators;
И переименовать в ReuestsValidators

2024-08-23 09:13 UTC, oleggolen commented on WebApi/WebApiAuthenticate/ModelsValidators/BaseValidators/PasswordValidator.cs
> +namespace WebApiAuthenticate.ModelsValidators.BaseValidators;
И переименовать в ReuestsValidators

2024-08-23 09:13 UTC, oleggolen commented on WebApi/WebApiAuthenticate/ModelsValidators/BaseValidators/UsernameValidator.cs
> +namespace WebApiAuthenticate.ModelsValidators.BaseValidators;
И переименовать в ReuestsValidators

2024-08-23 09:13 UTC, oleggolen commented on WebApi/WebApiAuthenticate/ModelsValidators/ChangeEmailValidator.cs
> +using WebApiAuthenticate.ModelsValidators.BaseValidators;
И переименовать в ReuestsValidators

2024-08-23 09:13 UTC, oleggolen commented on WebApi/WebApiAuthenticate/ModelsValidators/ChangePasswordValidator.cs
> +namespace WebApiAuthenticate.ModelsValidators;
И переименовать в ReuestsValidators

2024-08-23 09:13 UTC, oleggolen commented on WebApi/WebApiAuthenticate/ModelsValidators/ChangeUsernameValidator.cs
> +namespace WebApiAuthenticate.ModelsValidators;
И переименовать в ReuestsValidators

2024-08-23 09:13 UTC, oleggolen commented on WebApi/WebApiAuthenticate/ModelsValidators/CreatingUserValidator.cs
> +namespace WebApiAuthenticate.ModelsValidators;
И переименовать в ReuestsValidators

2024-08-23 09:13 UTC, oleggolen commented on WebApi/WebApiAuthenticate/ModelsValidators/VerifyEmailValidator.cs
> +namespace WebApiAuthenticate.ModelsValidators;
И переименовать в ReuestsValidators

2024-08-23 09:13 UTC, oleggolen commented on WebApi/WebApiAuthenticate/Controllers/UsersController.cs
> +[Route("/api/v1/[controller]")]
Нет, тут всё правильно, как и должно быть

2024-08-23 09:13 UTC, oleggolen commented on WebApi/WebApiAuthenticate/Controllers/UsersController.cs
> +    [HttpGet("GetAll/")]
Лишний слеш в конце названия

2024-08-23 09:13 UTC, oleggolen commented on WebApi/WebApiAuthenticate/Controllers/UsersController.cs
> +    //При валидации используется ли возврат 400? надо ли делать атрибут?
Да, обязательно сделать аттрибут на такой исход

2024-08-23 09:13 UTC, oleggolen commented on WebApi/WebApiAuthenticate/Controllers/UsersController.cs
> +    [HttpPut("ChangeUsername/")]
Лишний слеш

2024-08-23 09:13 UTC, oleggolen commented on WebApi/WebApiAuthenticate/Controllers/UsersController.cs
> +    [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
Добавить аатрибут на возможный результат 400

2024-08-23 09:13 UTC, oleggolen commented on WebApi/WebApiAuthenticate/Controllers/UsersController.cs
> +    [HttpPut("ChangePassword/")]
Лишний слеш

2024-08-23 09:13 UTC, oleggolen commented on WebApi/WebApiAuthenticate/Controllers/UsersController.cs
> +    [HttpPost("ChangeEmail/")]
Лишний слеш

2024-08-23 09:13 UTC, oleggolen commented on WebApi/WebApiAuthenticate/Controllers/UsersController.cs
> +        return BadRequest(); //что вернуть? Если не создалось в целом исключительная ситуация?
Можно так и оставить

2024-08-23 09:13 UTC, oleggolen commented on WebApi/WebApiAuthenticate/Controllers/UsersController.cs
> +    [HttpPut("VerifyEmail/")]
Лишний слеш

2024-08-23 09:13 UTC, oleggolen commented on WebApi/WebApiAuthenticate/Controllers/UsersController.cs
> +    [HttpPost("ChangeEmail/")]
Здесь для обновления данных используем метод Put

2024-08-23 14:08 UTC, NikeTorchwood commented on Application/Repositories.Abstractions/IBaseRepository.cs
> +public interface IBaseRepository<T, in TId>
поправил

2024-08-23 14:09 UTC, NikeTorchwood commented on Application/Services.Abstractions/IPasswordHasher.cs
> +    public bool VerifyHashedPassword(string password, string hashedPassword);
исправил

2024-08-25 19:06 UTC, m-a-ilnitsky requested changes
Согласен с большинством замечаний Олега и Юрия, кроме тех где явно указал иное.
В целом, круто, видно что проделана большая работа

2024-08-25 20:01 UTC, NikeTorchwood commented on Domain/Domain.ValueObjects/ValueObjects/Username.cs
> +            $"Invalid username  length. the minimum number of alphanumeric characters is equal to {MinNameLength}. Username value: {value}");
он там есть

2024-08-25 20:03 UTC, NikeTorchwood commented on Infrastructure/PasswordHasher/CustomPasswordHasher.cs
> +        var salt = BCrypt.Net.BCrypt.GenerateSalt(WorkFactor); // указываю явно, потому что только одна
Михаил прав

2024-08-25 20:03 UTC, NikeTorchwood commented on Infrastructure/PasswordHasher/CustomPasswordHasher.cs
> +        return BCrypt.Net.BCrypt.Verify(password, hashedPassword, EnhancedEntropy, HashType);
коммент выше

2024-08-25 20:03 UTC, NikeTorchwood commented on Infrastructure/PasswordHasher/CustomPasswordHasher.cs
> +        var hashedPassword = BCrypt.Net.BCrypt.HashPassword(password, salt, EnhancedEntropy, HashType);
коммент выше

2024-08-25 20:08 UTC, NikeTorchwood commented on Infrastructure/Repositories.Implementations/InMemoryRepository/BaseInMemoryRepository.cs
> +        return Task.FromResult(Entities.AsEnumerable());
на прошлых примерах это и использовал, было сказано что нужно вернуть AsEnumerable()

2024-08-25 20:15 UTC, m-a-ilnitsky commented on Domain/Domain.ValueObjects/ValueObjects/Username.cs
> +            $"Invalid username  length. the minimum number of alphanumeric characters is equal to {MinNameLength}. Username value: {value}");
Просто посмотри строчки 30 и 34, в строке 34 нужен еще один таб

2024-08-25 20:24 UTC, NikeTorchwood commented on Domain/Domain.ValueObjects/ValueObjects/Username.cs
> +            $"Invalid username  length. the minimum number of alphanumeric characters is equal to {MinNameLength}. Username value: {value}");
увидел

2024-08-26 08:31 UTC, NikeTorchwood commented on Infrastructure/EntityFramework/EntityFrameworkInstaller.cs
> +}
кросивенько

2024-08-26 13:47 UTC, closed without merging