принимаем не глядя нет времени объяснять
IT-Siberians/AuthenticationMicroservice pull request #27
Opened 2024-11-06 18:08 UTC by NikeTorchwood

2024-11-07 15:30 UTC, oleggolen requested changes
Ну в целом всё уже хорошо, теперь последние правки до идеального кода

2024-11-07 15:30 UTC, oleggolen commented on Application/Services.Implementations/NotificationService.cs
> +        var emailPublishModel = new ConfirmationEmailEvent(newEmail.Value, user.Username.Value, new Uri($"http://localhost/{code}"), culture);// исправить
Необходимо сделать нормальный построитель ссылки с помощью паттерна строитель

2024-11-07 15:30 UTC, oleggolen commented on Application/Services.Implementations/UserValidationService.cs
>      }
Сделать стрелочную функцию

2024-11-07 15:30 UTC, oleggolen commented on Application/Services.Implementations/VerificationCodeService.cs
> +        }
Сделать стрелочную функцию

2024-11-07 15:30 UTC, oleggolen commented on Application/Services.Implementations/VerificationCodeService.cs
Добавить документацию к коду в этом классе

2024-11-07 15:30 UTC, oleggolen commented on Domain/Domain.ValueObjects/ValueObjects/Username.cs
Тогда уж тут всё в модный современный switch обернуть раз уже пошла такая жара

2024-11-07 15:30 UTC, oleggolen commented on Infrastructure/Repositories.Implementations/RedisRepositories/VerificationCodeRepository.cs
> +    }
Стрелочные функции и документация

2024-11-07 15:30 UTC, oleggolen commented on WebApi/WebApiAuthenticate/Controllers/ConfirmsController.cs
>              if (!isAvailableEmail)
Убрать лишние скобки

2024-11-07 15:30 UTC, oleggolen commented on WebApi/WebApiAuthenticate/Controllers/ConfirmsController.cs
> +            return Ok("The email has been successfully confirmed");
Можно просто вернуть 204 по положительному статус коджу и так понятно, что он подтверждён

2024-11-07 15:30 UTC, oleggolen commented on WebApi/WebApiAuthenticate/Controllers/UsersController.cs
Убрать лишние скобки в этом файле

2024-11-07 15:30 UTC, oleggolen commented on WebApi/WebApiAuthenticate/Requests/ConfirmEmailRequest.cs
> +    string NewEmail, int Code) : BaseRequest<Guid>(Id);
Лучше сделать беззнаковый илин или вообще ushort

2024-11-07 15:30 UTC, oleggolen commented on WebApi/WebApiAuthenticate/appsettings.json
>    },
Убрать это всё в переменные окружения

2024-11-11 04:21 UTC, Barmalej24 approved these changes

2024-11-11 04:21 UTC, Barmalej24 commented on Application/Services.Implementations/UserValidationService.cs
>      }
согласен

2024-11-11 04:21 UTC, Barmalej24 commented on Application/Services.Implementations/UserValidationService.cs
>      }
Можно сделать стрелочную функцию

2024-11-11 04:21 UTC, Barmalej24 commented on Application/Services.Implementations/VerificationCodeService.cs
согласен

2024-11-11 04:21 UTC, Barmalej24 commented on WebApi/WebApiAuthenticate/Controllers/ConfirmsController.cs
лишнии скобки в  if конструкциях

2024-11-11 04:21 UTC, Barmalej24 commented on WebApi/WebApiAuthenticate/appsettings.json
>    },
согласен

2024-11-15 16:39 UTC, NikeTorchwood commented on Domain/Domain.ValueObjects/ValueObjects/Username.cs
не понял о чем речь

2024-11-15 16:41 UTC, NikeTorchwood commented on WebApi/WebApiAuthenticate/Requests/ConfirmEmailRequest.cs
> +    string NewEmail, int Code) : BaseRequest<Guid>(Id);
решено в gd-276

2024-11-15 17:25 UTC, ConstantinProg approved these changes
Тяжёлые времена требуют экстроординарных мер

2024-11-16 04:42 UTC, Barmalej24 approved these changes
Есть спорные моменты, автоформатирование можно и применить..

2024-11-16 17:23 UTC, merged