Task/gd 129
IT-Siberians/AuthenticationMicroservice pull request #4
Opened 2024-08-27 16:18 UTC by NikeTorchwood

fix conflicts

2024-08-27 22:18 UTC, m-a-ilnitsky approved these changes
В общем есть еще что исправлять.
Но на всякий случай заопрувил, может Олег позволит исправлять в другой ветке

2024-08-27 22:18 UTC, m-a-ilnitsky commented on WebApi/WebApiAuthenticate/RequestsValidators/ObjectsValidators/UsernameValidator.cs
> +    private const string ValidNamePattern = "(^[a-zA-Z_-]+$)";
Этот же шаблон и эти же константы используются используется в Username валуэ-обджекте.
Лучше здесь использовать константы из самого Username, достаточно сделать их публичными.

И странно что в одних местах у имён констант нотация из C# а в других нотация из Java

2024-08-27 22:18 UTC, m-a-ilnitsky commented on WebApi/WebApiAuthenticate/RequestsValidators/ObjectsValidators/UsernameValidator.cs
> +    private const int MaxNameLength = 30;
С учётом контекста, я бы сократил имена до MinLength и MaxLength

2024-08-27 22:18 UTC, m-a-ilnitsky commented on WebApi/WebApiAuthenticate/Responses/UserReadResponse.cs
> +public class UserReadResponse
UserReadResponse - а тут точно нужно слово Read?
Синтаксис имени похож на случай когда в имени DTO указывают название метода + "запрос/ответ".
Возможно тогда правильнее назвать ReadUserResponse или GetUserResponse.
Но это не точно)))

2024-08-28 05:26 UTC, oleggolen commented on WebApi/WebApiAuthenticate/Program.cs
> +    throw new InvalidOperationException("������ ����������� 'UsersDb' �� ����� ���� null ��� ������.");
Не надо писать сообщения к исключениям на русском или со специальными символами

2024-08-28 05:28 UTC, oleggolen commented on WebApi/WebApiAuthenticate/Responses/UserReadResponse.cs
> +    public AccountStatuses AccountStatus { get; init; }
Если используется FluentValidation, то смысла писать валидацию с помощью аттрибутов не имеет абсолютно никакого смысла, чтобы компилятор не давал предупреждения, также как и сам .NET отрабатывал без валидации проверку на то, что там не null лучше использовать ключевое слово required

2024-08-28 05:29 UTC, oleggolen commented on WebApi/WebApiAuthenticate/Responses/UserReadResponse.cs
> +public class UserReadResponse
Я бы просто назвал USerResponse, всё-таки тут просто информация о пользователе

2024-08-28 05:30 UTC, oleggolen commented on WebApi/WebApiAuthenticate/RequestsValidators/VerifyEmailValidator.cs
> +    }
Лучше эту логику вынести из валидатора, а сделать в бизнес логики, чтобы сохранять в базе данных когда и кому что мы выдавали для проверки

2024-08-28 05:32 UTC, oleggolen commented on WebApi/WebApiAuthenticate/RequestsValidators/ObjectsValidators/EmailValidator.cs
> +    }
Значит надо вынести отсюда и проверить это просто в конроллере, потому что это будет грузить веб-сервер очень сильно, а это плохо

2024-08-28 05:32 UTC, oleggolen commented on WebApi/WebApiAuthenticate/RequestsValidators/ObjectsValidators/EmailValidator.cs
> +    private const string ValidEmailPattern = @"[.\-_a-z0-9]+@([a-z0-9][\-a-z0-9]+\.)+[a-z]{2,6}";
Предлагаю эти штуки вынести в публичные хелперы, чтобы была возможность использовать на всех слоях

2024-08-28 05:33 UTC, oleggolen commented on WebApi/WebApiAuthenticate/RequestsValidators/ObjectsValidators/EmailValidator.cs
> +    private readonly IUserChangeValidationService _service;
Убрать из валидатора, так как валидатор ничего не должен знать о бизнес логике

2024-08-28 05:33 UTC, oleggolen commented on WebApi/WebApiAuthenticate/RequestsValidators/CreatingUserValidator.cs
> +    public CreatingUserValidator(IUserChangeValidationService service)
Убрать из валидатора, так как валидатор ничего не должен знать про бизнес-логику

2024-08-28 05:33 UTC, oleggolen commented on WebApi/WebApiAuthenticate/RequestsValidators/CreatingUserValidator.cs
> +            .SetValidator(new EmailValidator(service));
Убрать из валидатора

2024-08-28 05:34 UTC, oleggolen commented on WebApi/WebApiAuthenticate/RequestsValidators/ObjectsValidators/UsernameValidator.cs
> +    private const string ValidNamePattern = "(^[a-zA-Z_-]+$)";
Вынести вот это всё в публичные хелперы для того, чтобы была возможность использовать на всех слоях

2024-08-28 05:35 UTC, oleggolen commented on WebApi/WebApiAuthenticate/RequestsValidators/ObjectsValidators/UsernameValidator.cs
> +    }
Убрать из валидатора и перенести просто в контроллер

2024-08-28 05:35 UTC, oleggolen commented on WebApi/WebApiAuthenticate/RequestsValidators/ObjectsValidators/UsernameValidator.cs
> +    private readonly IUserChangeValidationService _service;
Убрать из валидатора

2024-08-28 05:35 UTC, oleggolen commented on WebApi/WebApiAuthenticate/RequestsValidators/ChangeUsernameValidator.cs
> +            .SetValidator(new UsernameValidator(service));
Убрать из валидатора

2024-08-28 06:01 UTC, NikeTorchwood commented on WebApi/WebApiAuthenticate/RequestsValidators/ObjectsValidators/UsernameValidator.cs
> +    private const string ValidNamePattern = "(^[a-zA-Z_-]+$)";
но тогда же Слой Domain получит зависимости? или их прям в домейн класть?

2024-08-28 06:03 UTC, NikeTorchwood commented on WebApi/WebApiAuthenticate/Responses/UserReadResponse.cs
> +public class UserReadResponse
она та что для чтения, там нет пока инфы о удален ли пользователь или залогинен, поэтому Read, чтобы подчеркнуть что она для чтения

2024-08-28 06:06 UTC, NikeTorchwood commented on WebApi/WebApiAuthenticate/Responses/UserReadResponse.cs
> +    public AccountStatuses AccountStatus { get; init; }
здесь я неправильно прошлое ревью понял

2024-08-28 06:07 UTC, NikeTorchwood commented on WebApi/WebApiAuthenticate/RequestsValidators/VerifyEmailValidator.cs
> +    }
нам это надо в бд хранить? планируется шифровать при создании ссылки и в ссылку вкладываться, дальше при подтверждении непосредственно расшифровать и получить

2024-08-28 06:27 UTC, oleggolen requested changes
В целом уже всё практически идеально, остались только мелкие косметические правки по исключениям, типам исключений, обязательности свойств. С CansellationToken'ами нужно быть аккуратнее, так как можно преобрести не оптимизации, а к чертям валить сервер при отмене тех или иных методов, поэтому лучше использовать более мягкие проверки с возвратами и прерываниями методов, а также не использовать асинхронные методы, в синхронном контектсте, лучше такие проверки перенести в сам контроллер или в бизнес логнику. Очень надеюсь, что указанные мною комментарии помогут полностью соблюдать структуру чистой архитектуры, аккуратно работать с многопоточностью и писать чистый код по SOLID принципам и DDD

2024-08-28 06:27 UTC, oleggolen commented on Infrastructure/Repositories.Implementations/EntityFrameworkRepositories/BaseEntityFrameworkRepository.cs
> +            throw new ArgumentNullException(nameof(id));
Я бы вообще убрал отсюда проверку на null и бросание исключение, можно и false вернуть, в принципе и так оставить только переписать в более современный вид

2024-08-28 06:27 UTC, oleggolen commented on Domain/Domain.ValueObjects/ValueObjects/Username.cs
> +    private const string VALID_USERNAME_PATTERN = "(^[a-zA-Z_-]+$)";
Вынести это всё в публичные хелперы для того, чтобы можно было проверять на других слоях

2024-08-28 06:27 UTC, oleggolen commented on Domain/Domain.ValueObjects/ValueObjects/Username.cs
> +        var match = Regex.Match(value, VALID_USERNAME_PATTERN, RegexOptions.IgnoreCase);
Тут можно переписать в более современный синтаксис

2024-08-28 06:27 UTC, oleggolen commented on Domain/Domain.ValueObjects/ValueObjects/Email.cs
> +    private const string VALID_EMAIL_PATTERN = @"[.\-_a-z0-9]+@([a-z0-9][\-a-z0-9]+\.)+[a-z]{2,6}";
Вынести это всё в публичные хелперы для того, чтобы это можно было использовать на других слоях, и не уверен, что 255 символов для Email - это хорошее решение, кажется, что слишком много

2024-08-28 06:27 UTC, oleggolen commented on Domain/Domain.ValueObjects/ValueObjects/Email.cs
> +        var match = Regex.Match(value, VALID_EMAIL_PATTERN, RegexOptions.IgnoreCase);
Переписать в более современный синтаксис

2024-08-28 06:27 UTC, oleggolen commented on Domain/Domain.ValueObjects/ValueObject.cs
> +public abstract class ValueObject<T>
Добавить различные перегрузки операторов сравнения, методов Equals, ToString для того, чтобы на других слоях уже можно было пользоваться ими, а не влазить внутрь класса

2024-08-28 06:27 UTC, oleggolen commented on Domain/Domain.ValueObjects/Exceptions/UsernameExceptions/UsernameMaxLengthException.cs
> +    ErrorDomainMessages.USERNAME_LONGER_MAX_LENGTH_ERROR);
Тут скорее стоит сформировать сообщение к исключению более корректно, а не использовать переданную строку. То есть сделать параметрами текущую длинну, тип объекта и требуемую длинну и с помощью интерполяции строк получить максимально детальное и понятное соощение

2024-08-28 06:27 UTC, oleggolen commented on Domain/Domain.ValueObjects/Exceptions/UsernameExceptions/UsernameMinLengthException.cs
> +    ErrorDomainMessages.USERNAME_SHORTER_MIN_LENGTH_ERROR);
Тут скорее стоит сформировать сообщение к исключению более корректно, а не использовать переданную строку. То есть сделать параметрами текущую длинну, тип объекта и требуемую длинну и с помощью интерполяции строк получить максимально детальное и понятное соощение

2024-08-28 06:27 UTC, oleggolen commented on Domain/Domain.ValueObjects/Exceptions/UsernameExceptions/UsernameEmptyException.cs
> +        : ArgumentNullException(paramName: nameof(value), message: ErrorDomainMessages.USERNAME_EMPTY_STRING_ERROR);
Здесь вот не соглашусь, так как само название исключения достаточно информативно, можно оставить так, ну или всё же добавить параметр с названием параметра исходного класса, вызвавшего исключение

2024-08-28 06:27 UTC, oleggolen commented on Domain/Domain.ValueObjects/Exceptions/PasswordHashExceptions/PasswordHashEmptyException.cs
> +    : ArgumentNullException(paramName: nameof(value), message: ErrorDomainMessages.PASSWORDHASH_EMPTY_ERROR);
Тут тоже достаточно информативное название самого исключения, но всё же стоит параметром добавить имя параметра исходного класса, вызвашего исключение

2024-08-28 06:27 UTC, oleggolen commented on Domain/Domain.ValueObjects/Exceptions/EmailExceptions/EmailEmptyException.cs
> +    : ArgumentNullException(paramName: nameof(value), message: ErrorDomainMessages.EMAIL_EMPTY_ERROR);
Да, тут согласен, что можно либо вообще убрать этот параметр, так как название самого исключения достаточно информативно, либо добавить ещё одним параметром наззвание поля, вызвавшего исключение, и таким образом вернуться к стандартной логике .NET

2024-08-28 06:27 UTC, oleggolen commented on Application/Services.Implementations/Exceptions/UserNotCreatedException.cs
> +internal class UserNotCreatedException() : NullReferenceException(ErrorApplicationMessages.USER_NOT_CREATE_ERROR);
Почему здесь NullReferenceException?

2024-08-28 06:27 UTC, oleggolen commented on Application/Services.Implementations/UserManagementService.cs
> +            throw new UserNotCreatedException();
Лучше просто вернуть null

2024-08-28 06:27 UTC, oleggolen commented on Application/Services.Contracts/BaseModel.cs
> +    public TId Id { get; init; }
Лучше просто использовать ключевое слово required или перейти на использование record

2024-08-28 06:27 UTC, oleggolen commented on Application/Services.Contracts/ChangePasswordModel.cs
> +    public string NewPassword { get; set; }
Лучше просто использовать ключевое слово required или перейти на использование record

2024-08-28 06:27 UTC, oleggolen commented on Application/Services.Contracts/ChangeUsernameModel.cs
> +    public string NewUsername { get; set; }
Лучше просто использовать ключевое слово required или перейти на использование record

2024-08-28 06:27 UTC, oleggolen commented on Application/Services.Contracts/CreateUserModel.cs
> +    public string Email { get; set; }
Лучше просто использовать ключевое слово required или перейти на использование record

2024-08-28 06:27 UTC, oleggolen commented on Application/Services.Contracts/MailConfirmationGenerationModel.cs
> +    public string NewEmail { get; set; }
Лучше просто использовать ключевое слово required или перейти на использование record

2024-08-28 06:27 UTC, oleggolen commented on Application/Services.Contracts/SetUserEmailModel.cs
> +    public string NewEmail { get; set; }
Лучше просто использовать ключевое слово required или перейти на использование record

2024-08-28 06:27 UTC, oleggolen commented on Application/Services.Contracts/UserReadModel.cs
> +    public AccountStatuses AccountStatus { get; set; }
Лучше просто использовать ключевое слово required или перейти на использование record

2024-08-28 06:27 UTC, oleggolen commented on Application/Services.Contracts/ValidatePasswordModel.cs
> +    public string Password { get; set; }
Лучше просто использовать ключевое слово required или перейти на использование record

2024-08-28 06:33 UTC, oleggolen commented on WebApi/WebApiAuthenticate/RequestsValidators/VerifyEmailValidator.cs
> +    }
Ну скорее всего да, так как REST API хранить информацию только на момент времени запроса, там просто не будет этих данных на момент валидации перехода по ссылке

2024-08-28 06:33 UTC, oleggolen commented on WebApi/WebApiAuthenticate/Responses/UserReadResponse.cs
> +    public AccountStatuses AccountStatus { get; init; }
Ок

2024-08-28 06:33 UTC, oleggolen commented on WebApi/WebApiAuthenticate/Responses/UserReadResponse.cs
> +public class UserReadResponse
Лучше всё же это убрать

2024-08-28 06:34 UTC, oleggolen commented on WebApi/WebApiAuthenticate/RequestsValidators/ObjectsValidators/UsernameValidator.cs
> +    private const string ValidNamePattern = "(^[a-zA-Z_-]+$)";
Такие зависимости можно в домен, где всякие статические константы, енумы и прочая такая фигня, поэтому их можно вынести в отдельный проект Common, как у меня это сделано

2024-08-28 09:12 UTC, m-a-ilnitsky approved these changes
В общем есть еще что исправлять.
Но на всякий случай заопрувил, может Олег позволит исправлять в другой ветке

Добавил несколько комментариев

2024-08-28 09:12 UTC, m-a-ilnitsky commented on Infrastructure/Repositories.Implementations/EntityFrameworkRepositories/BaseEntityFrameworkRepository.cs
> +            throw new ArgumentNullException(nameof(id));
Здесь без проверки на null не обойтись, т.к. проверяется не аргумента, а результат метода GetByIdAsync, который может вернуть null

2024-08-28 09:12 UTC, m-a-ilnitsky commented on Infrastructure/Repositories.Implementations/InMemoryRepository/InMemoryUserRepository.cs
> +        return await Task.Run(() => Entities.FirstOrDefault(u => u.Email.Value == email), cancellationToken);
Это предположение.
Если в сущностях email хранится в нормализованном виде приведенном к одному регистру, а в строке аргумента хотя бы одна буква в другом регистре, то не сработает.
Если в сущностях вообще нет нормализации, то такое сравнение строк через == вообще бессмысленно использовать.
Если где-то обе строки приводятся к единому формату, то нормально и так

2024-08-28 10:30 UTC, m-a-ilnitsky commented on Domain/Domain.ValueObjects/ValueObjects/Username.cs
> +            throw new UsernameInvalidCharacterException();
Здесь в исключение лучше передать само значение имени, чтобы можно было посмотреть какие именно неправильные символы оказались в имени

2024-08-29 16:42 UTC, NikeTorchwood commented on WebApi/WebApiAuthenticate/RequestsValidators/VerifyEmailValidator.cs
> +    }
это перенес в сервис, для сохранения своей логики

Как будет выглядеть взаимодействие с этим методом

при создании пользователя/смены почты
контроллер=>сервис создания ссылки=>шифрование ссылки(как хэш), куда уже кладется время создания=>отправка в сервис почты=>почта пользователя

там будет [host]/api/v1/Users/VerifyEmail/[ссылка в зашифрованном виде]=>дешифрация=>VerifyEmailRequest=>дальше оттуда достается время

так я планирую избежать использование БД для подтверждения почты

2024-08-29 16:52 UTC, closed without merging